// <auto-generated />
using System;
using HomeGroup.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeGroup.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511123113_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeGroup.API.Models.Entities.Attendance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("HomeGroupId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("MeetingDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WasPresent")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("HomeGroupId");

                    b.HasIndex("PersonId", "HomeGroupId", "MeetingDate")
                        .IsUnique();

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.HomeGroupEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long?>("LeaderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("MeetingDay")
                        .HasColumnType("text");

                    b.Property<string>("MeetingTime")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LeaderId");

                    b.ToTable("HomeGroups");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.HomeGroupMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("HomeGroupId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HomeGroupId");

                    b.HasIndex("PersonId", "HomeGroupId")
                        .IsUnique();

                    b.ToTable("HomeGroupMembers");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Повний доступ до системи",
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Адміністратор системи",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.UserHomeGroup", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("HomeGroupId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "HomeGroupId");

                    b.HasIndex("HomeGroupId");

                    b.ToTable("UserHomeGroups");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.Attendance", b =>
                {
                    b.HasOne("HomeGroup.API.Models.Entities.HomeGroupEntity", "HomeGroup")
                        .WithMany("Attendances")
                        .HasForeignKey("HomeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeGroup.API.Models.Entities.Person", "Person")
                        .WithMany("Attendances")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeGroup");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.HomeGroupEntity", b =>
                {
                    b.HasOne("HomeGroup.API.Models.Entities.Person", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.HomeGroupMember", b =>
                {
                    b.HasOne("HomeGroup.API.Models.Entities.HomeGroupEntity", "HomeGroup")
                        .WithMany("Members")
                        .HasForeignKey("HomeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeGroup.API.Models.Entities.Person", "Person")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeGroup");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.User", b =>
                {
                    b.HasOne("HomeGroup.API.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.UserHomeGroup", b =>
                {
                    b.HasOne("HomeGroup.API.Models.Entities.HomeGroupEntity", "HomeGroup")
                        .WithMany("UserHomeGroups")
                        .HasForeignKey("HomeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeGroup.API.Models.Entities.User", "User")
                        .WithMany("UserHomeGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.HomeGroupEntity", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Members");

                    b.Navigation("UserHomeGroups");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.Person", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("GroupMemberships");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.User", b =>
                {
                    b.Navigation("UserHomeGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
