// <auto-generated />
using System;
using HomeGroup.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeGroup.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513071506_AddNextMeetingOverrideAndMeetingMeta")]
    partial class AddNextMeetingOverrideAndMeetingMeta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeGroup.API.Models.Entities.Attendance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("HomeGroupId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("MeetingDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WasPresent")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("HomeGroupId");

                    b.HasIndex("PersonId", "HomeGroupId", "MeetingDate")
                        .IsUnique();

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.AttendanceMeta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer");

                    b.Property<string>("GuestInfo")
                        .HasColumnType("text");

                    b.Property<long>("HomeGroupId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("MeetingDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("HomeGroupId", "MeetingDate")
                        .IsUnique();

                    b.ToTable("AttendanceMetas");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.ChurchEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChurchEvents");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.GroupEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<long>("HomeGroupId")
                        .HasColumnType("bigint");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HomeGroupId");

                    b.ToTable("GroupEvents");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.HomeGroupCustomField", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("HomeGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HomeGroupId");

                    b.ToTable("HomeGroupCustomFields");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.HomeGroupEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long?>("LeaderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("MeetingDay")
                        .HasColumnType("text");

                    b.Property<string>("MeetingTime")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NextMeetingOverrideDate")
                        .HasColumnType("text");

                    b.Property<string>("TelegramGroupId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LeaderId");

                    b.ToTable("HomeGroups");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.HomeGroupMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("HomeGroupId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HomeGroupId");

                    b.HasIndex("PersonId", "HomeGroupId")
                        .IsUnique();

                    b.ToTable("HomeGroupMembers");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.HomeMeetingPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AppliedTemplateName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("HomeGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("MeetingDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HomeGroupId", "MeetingDate")
                        .IsUnique();

                    b.ToTable("MeetingPlans");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.MeetingPlanBlock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Info")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<long>("PlanId")
                        .HasColumnType("bigint");

                    b.Property<string>("Responsible")
                        .HasColumnType("text");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("MeetingPlanBlocks");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OversightInfo")
                        .HasColumnType("text");

                    b.Property<long?>("OversightUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<long?>("PrimaryGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OversightUserId");

                    b.HasIndex("PrimaryGroupId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.PersonCustomFieldValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FieldId")
                        .HasColumnType("bigint");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("PersonId", "FieldId")
                        .IsUnique();

                    b.ToTable("PersonCustomFieldValues");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.PlanTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlanTemplates");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.PlanTemplateBlock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Info")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Responsible")
                        .HasColumnType("text");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("PlanTemplateBlocks");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Color = "#2AAFCA",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Повний доступ до системи",
                            IsDefault = false,
                            IsSystem = true,
                            Name = "SuperAdmin",
                            PermissionsJson = "[\"*\"]"
                        },
                        new
                        {
                            Id = 2L,
                            Color = "#6366F1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Адміністратор системи",
                            IsDefault = true,
                            IsSystem = true,
                            Name = "Admin",
                            PermissionsJson = "[\"dashboard\",\"people\",\"groups\",\"admins\"]"
                        });
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("PrimaryGroupId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PrimaryGroupId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.UserHomeGroup", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("HomeGroupId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "HomeGroupId");

                    b.HasIndex("HomeGroupId");

                    b.ToTable("UserHomeGroups");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.Attendance", b =>
                {
                    b.HasOne("HomeGroup.API.Models.Entities.HomeGroupEntity", "HomeGroup")
                        .WithMany("Attendances")
                        .HasForeignKey("HomeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeGroup.API.Models.Entities.Person", "Person")
                        .WithMany("Attendances")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeGroup");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.AttendanceMeta", b =>
                {
                    b.HasOne("HomeGroup.API.Models.Entities.HomeGroupEntity", "HomeGroup")
                        .WithMany()
                        .HasForeignKey("HomeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeGroup");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.GroupEvent", b =>
                {
                    b.HasOne("HomeGroup.API.Models.Entities.HomeGroupEntity", "HomeGroup")
                        .WithMany()
                        .HasForeignKey("HomeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeGroup");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.HomeGroupCustomField", b =>
                {
                    b.HasOne("HomeGroup.API.Models.Entities.HomeGroupEntity", "HomeGroup")
                        .WithMany()
                        .HasForeignKey("HomeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeGroup");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.HomeGroupEntity", b =>
                {
                    b.HasOne("HomeGroup.API.Models.Entities.Person", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.HomeGroupMember", b =>
                {
                    b.HasOne("HomeGroup.API.Models.Entities.HomeGroupEntity", "HomeGroup")
                        .WithMany("Members")
                        .HasForeignKey("HomeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeGroup.API.Models.Entities.Person", "Person")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeGroup");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.HomeMeetingPlan", b =>
                {
                    b.HasOne("HomeGroup.API.Models.Entities.HomeGroupEntity", "HomeGroup")
                        .WithMany()
                        .HasForeignKey("HomeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeGroup");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.MeetingPlanBlock", b =>
                {
                    b.HasOne("HomeGroup.API.Models.Entities.HomeMeetingPlan", "Plan")
                        .WithMany("Blocks")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.Person", b =>
                {
                    b.HasOne("HomeGroup.API.Models.Entities.User", "OversightUser")
                        .WithMany()
                        .HasForeignKey("OversightUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HomeGroup.API.Models.Entities.HomeGroupEntity", "PrimaryGroup")
                        .WithMany()
                        .HasForeignKey("PrimaryGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OversightUser");

                    b.Navigation("PrimaryGroup");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.PersonCustomFieldValue", b =>
                {
                    b.HasOne("HomeGroup.API.Models.Entities.HomeGroupCustomField", "Field")
                        .WithMany("Values")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeGroup.API.Models.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.PlanTemplateBlock", b =>
                {
                    b.HasOne("HomeGroup.API.Models.Entities.PlanTemplate", "Template")
                        .WithMany("Blocks")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.User", b =>
                {
                    b.HasOne("HomeGroup.API.Models.Entities.HomeGroupEntity", "PrimaryGroup")
                        .WithMany()
                        .HasForeignKey("PrimaryGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PrimaryGroup");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.UserHomeGroup", b =>
                {
                    b.HasOne("HomeGroup.API.Models.Entities.HomeGroupEntity", "HomeGroup")
                        .WithMany("UserHomeGroups")
                        .HasForeignKey("HomeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeGroup.API.Models.Entities.User", "User")
                        .WithMany("UserHomeGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.UserRole", b =>
                {
                    b.HasOne("HomeGroup.API.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeGroup.API.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.HomeGroupCustomField", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.HomeGroupEntity", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Members");

                    b.Navigation("UserHomeGroups");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.HomeMeetingPlan", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.Person", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("GroupMemberships");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.PlanTemplate", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HomeGroup.API.Models.Entities.User", b =>
                {
                    b.Navigation("UserHomeGroups");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
